apiVersion: apps/v1
kind: Deployment
metadata:
  name: techmedicos-api
  namespace: techmedicos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: techmedicos-api
  template:
    metadata:
      labels:
        app: techmedicos-api
    spec:
      containers:
        - name: techmedicos-api
          image: g124soat/techmedicos-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "500m"
              memory: "500Mi"
          env:
            - name: DOTNET_ENVIRONMENT
              valueFrom: 
                configMapKeyRef:
                  name: techmedicos-api-configmap
                  key: DotnetEnviroment
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 5
            timeoutSeconds: 3

---
apiVersion: v1
kind: Service
metadata:
  name: techmedicos-api-service
  namespace: techmedicos
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
spec:
  selector:
    app: techmedicos-api
  ports:
    - protocol: TCP
      port: 5055
      targetPort: 8080
  type: LoadBalancer